version: '2'
services:

  web:
    container_name: 'web'
    image: primerevenue-docker.jfrog.io/app_perf:0.0.1
    command: 'bundle exec foreman start web'
    network_mode: "host"
    env_file:
      - ./.docker.env
    ports: 
      - 80

  worker: 
    container_name: 'worker'
    image: primerevenue-docker.jfrog.io/app_perf:0.0.1
    command: 'bundle exec foreman start worker'
    network_mode: "host"
    env_file:
      - ./.docker.env

