version: '2'
services:

  web:
    container_name: 'web'
    image: primerevenue-docker.jfrog.io/app_perf:0.0.1
    command: 'bundle exec foreman start web'
    network_mode: "host"
    env_file:
      - ./.docker.env
    ports: 
      - 5000:5000

  worker: 
    container_name: 'worker'
    image: primerevenue-docker.jfrog.io/app_perf:0.0.1
    command: 'bundle exec foreman start worker'
    network_mode: "host"
    environment:
      APP_PERF_HOST: localhost
      APP_PERF_LICENSE_KEY: 19509de2-d07d-470f-a8f5-aab940569d8 
      APP_PERF_PORT: 5000
      APP_PERF_SAMPLE_RATE: 20
      DEFAULT_DATA_RETENTION_HOURS: 1
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
    env_file:
      - ./.docker.env
    ports: 
      - 5000:5000   



